// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UploadImage(image, source string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"absolute top-24 left-5 \"><div class=\"relative w-28 h-28 group bg-base-800 rounded-full p-0.5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 = []any{`absolute flex items-center justify-center top-1 right-2
      bg-white text-black w-5 h-5 rounded-full cursor-pointer z-10 `, templ.KV(`hidden`, image == "")}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"remove-button\" onclick=\"removeImage()\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/upload_image.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">✖</div><!-- Hidden input to store the image data or filename --><input type=\"hidden\" id=\"image\" name=\"image\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(image)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/upload_image.templ`, Line: 9, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" alt=\"customer-image\"><!-- Image display logic -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if image != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img id=\"placeholder-image\" src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(image)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/upload_image.templ`, Line: 12, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" alt=\"customer-image\" class=\"w-full h-full object-center rounded-full bg-white\" onerror=\"this.onerror=null; this.src=&#39;/not-found.png&#39;;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			if source == "customer" {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img id=\"placeholder-image\" src=\"/not-found-person.png\" alt=\"Placeholder\" class=\"w-full h-full object-center rounded-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if source == "shop" {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<img id=\"placeholder-image\" src=\"/not-found-shop.png\" alt=\"Placeholder\" class=\"w-full h-full object-center rounded-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Upload button --><div onclick=\"document.getElementById(&#39;file-input&#39;).click()\" class=\"absolute inset-0 cursor-pointer bg-black rounded-full bg-opacity-50 flex flex-col items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300\"><i class=\"fa-solid fa-camera-retro\"></i> <button type=\"button\" class=\"mt-2 text-white bg-transparent border-none cursor-pointer text-lg\">Upload</button></div><!-- File input --><input type=\"file\" id=\"file-input\" name=\"file\" class=\"hidden\" onchange=\"previewImage(event)\"></div></div><script>\n  function previewImage(event) {\n    const reader = new FileReader();\n    reader.onload = function () {\n      const imgElement = document.getElementById('placeholder-image');\n      imgElement.src = reader.result;\n      document.getElementById('remove-button').classList.remove('hidden');\n    }\n    reader.readAsDataURL(event.target.files[0]);\n  }\n\n  function removeImage() {\n    document.getElementById('image').value = '';\n    const imgElement = document.getElementById('placeholder-image');\n    imgElement.src = '/not-found-person.png'; // Set back to placeholder image\n    document.getElementById('file-input').value = ''; // Clear file input\n    const removeButton = document.getElementById('remove-button')\n    removeButton.classList.add('hidden')\n  }\n\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
