// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package subscriptions

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/gonext-tech/internal/models"

func TableHeader(params models.ParamResponse) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<tr><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Membership</th><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Dates</th><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Amount</th><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Project</th><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Payment</th><th scope=\"col\" class=\"px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400\">Status</th></tr>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
